locale: "hu"
backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master

media_folder: "src/static/img/uploads"
public_folder: "/static/img/uploads"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Céges referenca"
    name: "corporate"
    folder: "src/references/corporate"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Cover Image"
        name: "image"
        widget: "image"
      - widget: select
        label: "tags"
        name: "tags"
        multiple: false
        create: true
        options: ["post_corporate"]
  - label: "Fesztivál referenca"
    name: "festival"
    folder: "src/references/festivals"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Cover Image"
        name: "image"
        widget: "image"
      - widget: select
        label: "tags"
        name: "tags"
        multiple: false
        create: true
        options: ["post_festival"]
